### ISSUE TITLE
SVG file parsing failed

### ISSUE THREAD

**Issue by xiaoxidong** [nour7/SSVGShape#1]
When I parse a svg file it goes wrong with SVG file parsing failed error, and it seems the problem is SVGModel.svgTree is empty.

**Comment by nourome** [comment]
Are you sure the SVG file is v1.1 with transform tag? can you post content of your SVG file?

**Comment by xiaoxidong** [comment]
My mistake, there is no transform tag.
Will it support the svg without transform tag？
